name: KMM CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests with Gradle
      run: ./gradlew test

    - name: Upload Android artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: app/build/outputs/apk/release/app-release.apk

  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adopt'

    - name: Install CocoaPods
      run: brew install cocoapods

    - name: Install pods
      run: cd iosApp && pod install

    - name: Build iOS app
      run: xcodebuild -workspace iosApp/iosApp.xcworkspace -scheme iosApp -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' build

    - name: Upload iOS artifact
      uses: actions/upload-artifact@v2
      with:
        name: ios-app
        path: iosApp/build/ios-app.ipa
